"""One-shot generator for binary fixture files.

Run from anywhere::

    python3 e2e/fixtures/_generate.py

This writes ``sample.pdf``, ``sample.docx``, and ``sample.png`` into
``e2e/fixtures/documents``. The output files are checked into git so the
test suite never regenerates them at runtime.
"""

from __future__ import annotations

import io
import struct
import zipfile
import zlib
from pathlib import Path

OUT = Path(__file__).resolve().parent / "documents"


def _minimal_pdf() -> bytes:
    """A hand-rolled minimal PDF 1.4 with a single text line.

    The text reads ``Acme sample PDF: hello from fake-fixture.`` Suitable
    for OCR / Docling extraction.
    """
    objects: list[bytes] = []

    def obj(num: int, body: bytes) -> bytes:
        return f"{num} 0 obj\n".encode() + body + b"\nendobj\n"

    # 1 catalog, 2 pages, 3 page, 4 font, 5 content stream
    catalog = b"<< /Type /Catalog /Pages 2 0 R >>"
    pages = b"<< /Type /Pages /Count 1 /Kids [3 0 R] >>"
    page = (
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] "
        b"/Contents 5 0 R /Resources << /Font << /F1 4 0 R >> >> >>"
    )
    font = b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>"
    text = b"BT /F1 18 Tf 72 720 Td (Acme sample PDF: hello from fake-fixture.) Tj ET"
    content = f"<< /Length {len(text)} >>\nstream\n".encode() + text + b"\nendstream"

    objects.append(obj(1, catalog))
    objects.append(obj(2, pages))
    objects.append(obj(3, page))
    objects.append(obj(4, font))
    objects.append(obj(5, content))

    buf = io.BytesIO()
    buf.write(b"%PDF-1.4\n%\xe2\xe3\xcf\xd3\n")
    offsets: list[int] = []
    for raw in objects:
        offsets.append(buf.tell())
        buf.write(raw)
    xref_pos = buf.tell()
    buf.write(f"xref\n0 {len(objects) + 1}\n".encode())
    buf.write(b"0000000000 65535 f \n")
    for off in offsets:
        buf.write(f"{off:010d} 00000 n \n".encode())
    buf.write(
        f"trailer\n<< /Size {len(objects) + 1} /Root 1 0 R >>\n"
        f"startxref\n{xref_pos}\n%%EOF\n".encode()
    )
    return buf.getvalue()


_DOCX_CONTENT_TYPES = (
    b'<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
    b'<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">'
    b'<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>'
    b'<Default Extension="xml" ContentType="application/xml"/>'
    b'<Override PartName="/word/document.xml" '
    b'ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>'
    b"</Types>"
)

_DOCX_RELS = (
    b'<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
    b'<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
    b'<Relationship Id="rId1" '
    b'Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" '
    b'Target="word/document.xml"/>'
    b"</Relationships>"
)

_DOCX_DOCUMENT = (
    b'<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
    b'<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">'
    b"<w:body>"
    b"<w:p><w:r><w:t>Acme sample DOCX</w:t></w:r></w:p>"
    b"<w:p><w:r><w:t>This document is generated by e2e/fixtures/_generate.py "
    b"and is suitable for Docling extraction.</w:t></w:r></w:p>"
    b"<w:p><w:r><w:t>The Acme Knowledge Platform supports DOCX, PDF, HTML, "
    b"Markdown, and plain text.</w:t></w:r></w:p>"
    b"</w:body>"
    b"</w:document>"
)


def _minimal_docx() -> bytes:
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("[Content_Types].xml", _DOCX_CONTENT_TYPES)
        zf.writestr("_rels/.rels", _DOCX_RELS)
        zf.writestr("word/document.xml", _DOCX_DOCUMENT)
    return buf.getvalue()


def _png_chunk(tag: bytes, data: bytes) -> bytes:
    crc = zlib.crc32(tag + data) & 0xFFFFFFFF
    return struct.pack(">I", len(data)) + tag + data + struct.pack(">I", crc)


def _minimal_png(width: int = 16, height: int = 16) -> bytes:
    signature = b"\x89PNG\r\n\x1a\n"
    ihdr = struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0)
    raw = b""
    for _y in range(height):
        raw += b"\x00" + b"\x4f\x97\xb3" * width  # filter byte + RGB pixels
    idat = zlib.compress(raw, 9)
    return (
        signature
        + _png_chunk(b"IHDR", ihdr)
        + _png_chunk(b"IDAT", idat)
        + _png_chunk(b"IEND", b"")
    )


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "sample.pdf").write_bytes(_minimal_pdf())
    (OUT / "sample.docx").write_bytes(_minimal_docx())
    (OUT / "sample.png").write_bytes(_minimal_png())
    print("wrote", OUT)


if __name__ == "__main__":
    main()
