"""bigRAG Python SDK."""

from __future__ import annotations

from bigrag._client import BigRAG, CollectionClient
from bigrag._core import BigRAGCore
from bigrag._errors import (
    APIConnectionError,
    APIError,
    APITimeoutError,
    AuthenticationError,
    BadRequestError,
    BigRAGError,
    InternalServerError,
    NotFoundError,
    RateLimitError,
    error_for_status,
)
from bigrag._files import FileInput, normalize_file_input
from bigrag._sse import parse_sse_stream
from bigrag._types import (
    AnalyticsResponse,
    BatchDeleteDocumentsResponse,
    BatchDeleteError,
    BatchGetDocumentsResponse,
    BatchQueryBody,
    BatchQueryItem,
    BatchQueryResponse,
    BatchQueryResultItem,
    BatchStatusResponse,
    Collection,
    CollectionListResponse,
    CollectionStatsResponse,
    CreateCollectionBody,
    CreateWebhookBody,
    CreateWebhookResponse,
    DeleteResponse,
    Document,
    DocumentChunk,
    DocumentChunkListResponse,
    DocumentListResponse,
    DocumentStats,
    DocumentStatus,
    EmbeddingModelInfo,
    EmbeddingModelListResponse,
    HealthResponse,
    MultiQueryBody,
    MultiQueryResponse,
    MultiQueryResult,
    PeriodStats,
    PlatformStatsResponse,
    ProgressEvent,
    QueryBody,
    QueryResponse,
    QueryResult,
    QueueStatsResponse,
    ReadinessResponse,
    S3IngestBody,
    S3IngestResponse,
    StatusResponse,
    TopQuery,
    UpdateCollectionBody,
    UpdateWebhookBody,
    UpsertResponse,
    UrlIngestBody,
    VectorEntry,
    Webhook,
    WebhookDelivery,
    WebhookDeliveryListResponse,
    WebhookListResponse,
    WebhookTestResponse,
)
from bigrag.resources import (
    CollectionsResource,
    DocumentsResource,
    QueryResource,
    VectorsResource,
    WebhooksResource,
)

__all__ = [
    # Client
    "BigRAG",
    "BigRAGCore",
    "CollectionClient",
    # Errors
    "APIConnectionError",
    "APIError",
    "APITimeoutError",
    "AuthenticationError",
    "BadRequestError",
    "BigRAGError",
    "InternalServerError",
    "NotFoundError",
    "RateLimitError",
    "error_for_status",
    # Files
    "FileInput",
    "normalize_file_input",
    # SSE
    "parse_sse_stream",
    # Resources
    "CollectionsResource",
    "DocumentsResource",
    "QueryResource",
    "VectorsResource",
    "WebhooksResource",
    # Types - Common
    "StatusResponse",
    "HealthResponse",
    "ReadinessResponse",
    "QueueStatsResponse",
    "DocumentStats",
    "PlatformStatsResponse",
    # Types - Collections
    "Collection",
    "CollectionListResponse",
    "CollectionStatsResponse",
    "CreateCollectionBody",
    "UpdateCollectionBody",
    # Types - Documents
    "Document",
    "DocumentListResponse",
    "DocumentChunk",
    "DocumentChunkListResponse",
    "DocumentStatus",
    "BatchStatusResponse",
    "BatchGetDocumentsResponse",
    "BatchDeleteError",
    "BatchDeleteDocumentsResponse",
    # Types - Query
    "QueryBody",
    "QueryResult",
    "QueryResponse",
    "MultiQueryBody",
    "MultiQueryResult",
    "MultiQueryResponse",
    "BatchQueryItem",
    "BatchQueryBody",
    "BatchQueryResultItem",
    "BatchQueryResponse",
    # Types - Vectors
    "VectorEntry",
    "UpsertResponse",
    "DeleteResponse",
    # Types - Webhooks
    "Webhook",
    "CreateWebhookBody",
    "CreateWebhookResponse",
    "UpdateWebhookBody",
    "WebhookListResponse",
    "WebhookDelivery",
    "WebhookDeliveryListResponse",
    "WebhookTestResponse",
    # Types - Analytics
    "PeriodStats",
    "TopQuery",
    "AnalyticsResponse",
    # Types - Embeddings
    "EmbeddingModelInfo",
    "EmbeddingModelListResponse",
    # Types - Ingestion Sources
    "UrlIngestBody",
    "S3IngestBody",
    "S3IngestResponse",
    # Types - SSE
    "ProgressEvent",
]
