from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Literal

from rag_computer.models.instance_settings import SettingGroup, SettingKind

SettingSource = Literal["default", "database", "bootstrap"]


@dataclass(frozen=True)
class SettingSpec:
    key: str
    group: SettingGroup
    label: str
    kind: SettingKind
    default: Any
    description: str
    options: tuple[str, ...] = ()
    min: float | None = None
    max: float | None = None
    secret: bool = False
    restart_required: bool = False


def _spec(
    key: str,
    group: SettingGroup,
    label: str,
    kind: SettingKind,
    default: Any,
    description: str,
    *,
    options: tuple[str, ...] = (),
    min: float | None = None,
    max: float | None = None,
    secret: bool = False,
    restart_required: bool = False,
) -> SettingSpec:
    return SettingSpec(
        key=key,
        group=group,
        label=label,
        kind=kind,
        default=default,
        description=description,
        options=options,
        min=min,
        max=max,
        secret=secret,
        restart_required=restart_required,
    )


SETTING_SPECS: tuple[SettingSpec, ...] = (
    _spec(
        "cors_origins",
        "security",
        "CORS origins",
        "string_list",
        [],
        "Browser origins allowed to call the API with credentials.",
    ),
    _spec(
        "trusted_proxies",
        "security",
        "Trusted proxies",
        "string_list",
        [],
        "CIDR ranges trusted for forwarded client IP headers.",
        restart_required=True,
    ),
    _spec(
        "session_cookie_secure",
        "security",
        "Secure session cookie",
        "bool",
        False,
        "Send the admin session cookie only over HTTPS.",
    ),
    _spec(
        "session_cookie_samesite",
        "security",
        "Session SameSite",
        "select",
        "lax",
        "Browser SameSite policy for admin sessions.",
        options=("lax", "strict", "none"),
    ),
    _spec(
        "session_cookie_domain",
        "security",
        "Session cookie domain",
        "string",
        None,
        "Optional cookie domain for split frontend and API deployments.",
    ),
    _spec(
        "allow_public_bind_in_prod",
        "security",
        "Allow public prod bind",
        "bool",
        False,
        "Allow RAG_COMPUTER_HOST=0.0.0.0 or :: when RAG_COMPUTER_ENV=prod.",
        restart_required=True,
    ),
    _spec(
        "allowed_embedding_base_urls",
        "security",
        "Allowed embedding base URLs",
        "string_list",
        [],
        "Explicit external embedding endpoints allowed by outbound URL policy.",
    ),
    _spec(
        "allow_private_embedding_base_urls",
        "security",
        "Private embedding URLs",
        "bool",
        False,
        "Allow embedding endpoints on private networks.",
    ),
    _spec(
        "allowed_chat_base_urls",
        "security",
        "Allowed chat base URLs",
        "string_list",
        [],
        "Explicit external chat endpoints allowed by outbound URL policy.",
    ),
    _spec(
        "allow_private_chat_base_urls",
        "security",
        "Private chat URLs",
        "bool",
        False,
        "Allow chat endpoints on private networks.",
    ),
    _spec(
        "allow_local_webhooks",
        "security",
        "Local webhook URLs",
        "bool",
        False,
        "Allow webhook delivery to loopback URLs.",
    ),
    _spec(
        "max_upload_size_mb",
        "ingestion",
        "Max upload size",
        "int",
        64,
        "Maximum size for a single uploaded document in MB.",
        min=1,
        max=10240,
    ),
    _spec(
        "max_batch_upload_size_mb",
        "ingestion",
        "Max batch upload size",
        "int",
        128,
        "Maximum aggregate size for a batch upload in MB.",
        min=1,
        max=102400,
    ),
    _spec(
        "max_upload_session_files",
        "ingestion",
        "Max upload session files",
        "int",
        10000,
        "Maximum files accepted by a resumable upload session.",
        min=1,
        max=1000000,
    ),
    _spec(
        "max_upload_session_size_mb",
        "ingestion",
        "Max upload session size",
        "int",
        102400,
        "Maximum aggregate size for a resumable upload session in MB.",
        min=1,
        max=1048576,
    ),
    _spec(
        "upload_session_upload_concurrency",
        "ingestion",
        "Upload session concurrency",
        "int",
        4,
        "Default browser upload concurrency for the admin UI.",
        min=1,
        max=64,
    ),
    _spec(
        "conversion_pdf_ocr_enabled",
        "ingestion",
        "PDF OCR",
        "bool",
        True,
        "OCR scanned PDFs when no embedded text is found.",
    ),
    _spec(
        "conversion_timeout",
        "ingestion",
        "Conversion timeout",
        "int",
        300,
        "Docling conversion timeout in seconds.",
        min=10,
        max=86400,
    ),
    _spec(
        "ingestion_workers",
        "ingestion",
        "Ingestion workers",
        "int",
        4,
        "Target worker concurrency for this API role.",
        min=1,
        max=256,
    ),
    _spec(
        "ingestion_batch_size",
        "ingestion",
        "Ingestion batch size",
        "int",
        128,
        "Vector insert batch size for ingestion workers.",
        min=1,
        max=4096,
    ),
    _spec(
        "max_vector_upsert_count",
        "ingestion",
        "Max vector upsert count",
        "int",
        1000,
        "Maximum vectors accepted by one raw vector upsert request.",
        min=1,
        max=1000000,
    ),
    _spec(
        "max_vector_delete_count",
        "ingestion",
        "Max vector delete count",
        "int",
        10000,
        "Maximum vector IDs accepted by one raw vector delete request.",
        min=1,
        max=1000000,
    ),
    _spec(
        "max_vector_text_chars",
        "ingestion",
        "Max vector text chars",
        "int",
        100000,
        "Maximum text characters accepted on one raw vector entry.",
        min=0,
        max=10000000,
    ),
    _spec(
        "max_vector_metadata_bytes",
        "ingestion",
        "Max vector metadata bytes",
        "int",
        65536,
        "Maximum JSON metadata bytes accepted on one raw vector entry.",
        min=0,
        max=10485760,
    ),
    _spec(
        "queue_max_depth",
        "queue",
        "Queue max depth",
        "int",
        10000,
        "Maximum pending ingestion jobs before uploads are rejected.",
        min=1,
        max=10000000,
    ),
    _spec(
        "storage_backend",
        "storage",
        "Storage backend",
        "select",
        "local",
        "Document binary storage backend.",
        options=("local", "s3"),
        restart_required=True,
    ),
    _spec(
        "storage_s3_bucket",
        "storage",
        "S3 bucket",
        "string",
        "",
        "Bucket used when the storage backend is S3 or MinIO.",
        restart_required=True,
    ),
    _spec(
        "storage_s3_endpoint_url",
        "storage",
        "S3 endpoint URL",
        "string",
        None,
        "Optional MinIO or S3-compatible endpoint URL.",
        restart_required=True,
    ),
    _spec(
        "storage_s3_region",
        "storage",
        "S3 region",
        "string",
        "us-east-1",
        "S3 region for bucket operations.",
        restart_required=True,
    ),
    _spec(
        "storage_s3_prefix",
        "storage",
        "S3 prefix",
        "string",
        "",
        "Optional key prefix prepended to uploaded documents.",
        restart_required=True,
    ),
    _spec(
        "storage_s3_access_key_id",
        "storage",
        "S3 access key ID",
        "secret",
        None,
        "Optional static access key ID for S3-compatible storage.",
        secret=True,
        restart_required=True,
    ),
    _spec(
        "storage_s3_secret_access_key",
        "storage",
        "S3 secret access key",
        "secret",
        None,
        "Optional static secret access key for S3-compatible storage.",
        secret=True,
        restart_required=True,
    ),
    _spec(
        "storage_s3_force_path_style",
        "storage",
        "S3 path-style requests",
        "bool",
        False,
        "Use path-style bucket addressing for MinIO.",
        restart_required=True,
    ),
    _spec(
        "storage_signed_url_ttl_seconds",
        "storage",
        "Signed URL TTL",
        "int",
        900,
        "Default signed URL lifetime in seconds for future external file access.",
        min=60,
        max=604800,
    ),
    _spec(
        "backup_s3_bucket",
        "backups",
        "Backup S3 bucket",
        "string",
        "",
        "S3-compatible bucket for readable full-instance backups.",
    ),
    _spec(
        "backup_s3_endpoint_url",
        "backups",
        "Backup endpoint URL",
        "string",
        None,
        "Optional S3-compatible endpoint URL for Cloudflare R2 or MinIO.",
    ),
    _spec(
        "backup_s3_region",
        "backups",
        "Backup region",
        "string",
        "us-east-1",
        "S3 region for backup uploads.",
    ),
    _spec(
        "backup_s3_prefix",
        "backups",
        "Backup prefix",
        "string",
        "",
        "Optional prefix prepended to backup objects.",
    ),
    _spec(
        "backup_s3_access_key_id",
        "backups",
        "Backup access key ID",
        "secret",
        None,
        "Optional static access key ID for backup storage.",
        secret=True,
    ),
    _spec(
        "backup_s3_secret_access_key",
        "backups",
        "Backup secret access key",
        "secret",
        None,
        "Optional static secret access key for backup storage.",
        secret=True,
    ),
    _spec(
        "backup_s3_force_path_style",
        "backups",
        "Backup path-style requests",
        "bool",
        False,
        "Use path-style bucket addressing for backup storage.",
    ),
    _spec(
        "vector_store_provider",
        "vector_store",
        "Vector store provider",
        "select",
        "qdrant",
        "Instance-level vector backend.",
        options=("qdrant", "s3_vectors", "turbopuffer"),
        restart_required=True,
    ),
    _spec(
        "qdrant_url",
        "vector_store",
        "Qdrant URL",
        "string",
        "http://localhost:6333",
        "Qdrant connection URL.",
        restart_required=True,
    ),
    _spec(
        "qdrant_api_key",
        "vector_store",
        "Qdrant API key",
        "secret",
        None,
        "Optional Qdrant API key.",
        secret=True,
        restart_required=True,
    ),
    _spec(
        "qdrant_connect_timeout_seconds",
        "vector_store",
        "Qdrant connect timeout",
        "int",
        10,
        "Qdrant startup connection timeout in seconds.",
        min=0,
        max=300,
        restart_required=True,
    ),
    _spec(
        "qdrant_required",
        "vector_store",
        "Require vector store",
        "bool",
        False,
        "Fail startup if the configured vector store cannot be reached.",
        restart_required=True,
    ),
    _spec(
        "s3_vectors_bucket",
        "vector_store",
        "S3 vector bucket",
        "string",
        "",
        "S3 vector bucket used when the vector store provider is S3 Vectors.",
        restart_required=True,
    ),
    _spec(
        "s3_vectors_region",
        "vector_store",
        "S3 Vectors region",
        "string",
        "us-east-1",
        "AWS region for S3 Vectors.",
        restart_required=True,
    ),
    _spec(
        "s3_vectors_index_prefix",
        "vector_store",
        "S3 Vectors index prefix",
        "string",
        "rag_computer_",
        "Prefix prepended to S3 vector index names.",
        restart_required=True,
    ),
    _spec(
        "s3_vectors_access_key_id",
        "vector_store",
        "S3 Vectors access key ID",
        "secret",
        None,
        "Optional static access key ID for S3 Vectors.",
        secret=True,
        restart_required=True,
    ),
    _spec(
        "s3_vectors_secret_access_key",
        "vector_store",
        "S3 Vectors secret access key",
        "secret",
        None,
        "Optional static secret access key for S3 Vectors.",
        secret=True,
        restart_required=True,
    ),
    _spec(
        "turbopuffer_api_key",
        "vector_store",
        "turbopuffer API key",
        "secret",
        None,
        "turbopuffer API key.",
        secret=True,
        restart_required=True,
    ),
    _spec(
        "turbopuffer_region",
        "vector_store",
        "turbopuffer region",
        "string",
        "aws-us-east-1",
        "turbopuffer region slug.",
        restart_required=True,
    ),
    _spec(
        "turbopuffer_namespace_prefix",
        "vector_store",
        "turbopuffer namespace prefix",
        "string",
        "rag_computer_",
        "Prefix prepended to turbopuffer namespace names.",
        restart_required=True,
    ),
    _spec(
        "qdrant_search_ef",
        "vector_store",
        "Qdrant search ef",
        "int",
        None,
        "Optional Qdrant HNSW search ef override.",
        min=1,
        max=10000,
        restart_required=True,
    ),
    _spec(
        "embedding_concurrency",
        "search",
        "Embedding concurrency",
        "int",
        8,
        "Maximum concurrent embedding requests per provider endpoint.",
        min=1,
        max=1024,
    ),
    _spec(
        "collection_cache_ttl",
        "search",
        "Collection cache TTL",
        "int",
        30,
        "Collection metadata cache TTL in seconds.",
        min=0,
        max=86400,
    ),
    _spec(
        "query_embedding_cache_ttl",
        "search",
        "Query embedding cache TTL",
        "int",
        300,
        "Query embedding cache TTL in seconds.",
        min=0,
        max=604800,
    ),
    _spec(
        "embedding_cache_mode",
        "security",
        "Embedding cache mode",
        "select",
        "encrypted",
        "Persistent chunk embedding cache behavior.",
        options=("encrypted", "disabled"),
    ),
    _spec(
        "query_result_cache_ttl",
        "search",
        "Query result cache TTL",
        "int",
        30,
        "Query result cache TTL in seconds.",
        min=0,
        max=86400,
    ),
    _spec(
        "embedding_provider",
        "search",
        "Default embedding provider",
        "select",
        "openai",
        "Fallback embedding provider for collections created without a preset.",
        options=("openai", "openai_compatible", "cohere", "voyage"),
    ),
    _spec(
        "embedding_model",
        "search",
        "Default embedding model",
        "string",
        "text-embedding-3-small",
        "Fallback embedding model for collections created without a preset.",
    ),
    _spec(
        "embedding_dimension",
        "search",
        "Default embedding dimension",
        "int",
        1536,
        "Fallback vector dimension for collections created without a preset.",
        min=1,
        max=100000,
    ),
    _spec(
        "embedding_base_url",
        "search",
        "Default embedding base URL",
        "string",
        None,
        "Optional fallback OpenAI-compatible embedding base URL.",
    ),
    _spec(
        "embedding_api_key",
        "search",
        "Default embedding API key",
        "secret",
        None,
        "Optional fallback provider key for collections created without a preset.",
        secret=True,
    ),
    _spec(
        "chat_provider",
        "chat",
        "Default chat provider",
        "select",
        "openai",
        "Default provider for new chat conversations.",
        options=("openai", "openai_compatible"),
    ),
    _spec(
        "chat_model",
        "chat",
        "Default chat model",
        "string",
        "gpt-4o-mini",
        "Default model for new chat conversations.",
    ),
    _spec(
        "chat_base_url",
        "chat",
        "Chat base URL",
        "string",
        None,
        "Optional OpenAI-compatible chat API base URL.",
    ),
    _spec(
        "chat_temperature",
        "chat",
        "Chat temperature",
        "float",
        0.2,
        "Default sampling temperature for chat completions.",
        min=0,
        max=2,
    ),
    _spec(
        "chat_max_history_messages",
        "chat",
        "Max chat history",
        "int",
        12,
        "Prior complete messages included in model context.",
        min=0,
        max=200,
    ),
    _spec(
        "chat_max_context_chars",
        "chat",
        "Max context characters",
        "int",
        120000,
        "Retrieved source characters included in model context.",
        min=1000,
        max=2000000,
    ),
    _spec(
        "webhook_delivery_timeout",
        "webhooks",
        "Delivery timeout",
        "int",
        10,
        "Webhook delivery timeout in seconds.",
        min=1,
        max=300,
    ),
    _spec(
        "webhook_retry_delays",
        "webhooks",
        "Retry delays",
        "int_list",
        [10, 30, 90],
        "Webhook retry delays in seconds.",
    ),
    _spec(
        "webhook_max_count",
        "webhooks",
        "Max webhooks",
        "int",
        50,
        "Maximum configured webhooks per instance.",
        min=0,
        max=10000,
    ),
    _spec(
        "query_log_retention_days",
        "retention",
        "Query log retention",
        "int",
        90,
        "Days to keep query logs.",
        min=1,
        max=3650,
    ),
    _spec(
        "access_log_retention_days",
        "retention",
        "Access log retention",
        "int",
        90,
        "Days to keep access logs.",
        min=1,
        max=3650,
    ),
    _spec(
        "webhook_delivery_retention_days",
        "retention",
        "Webhook delivery retention",
        "int",
        90,
        "Days to keep webhook delivery attempts.",
        min=1,
        max=3650,
    ),
    _spec(
        "progress_snapshot_retention_days",
        "retention",
        "Progress snapshot retention",
        "int",
        7,
        "Days to keep ingestion progress snapshots where durable snapshots are enabled.",
        min=1,
        max=365,
    ),
    _spec(
        "upload_session_item_retention_hours",
        "retention",
        "Upload session retention",
        "int",
        168,
        "Hours to keep upload-session item history.",
        min=1,
        max=87600,
    ),
    _spec(
        "embedding_cache_retention_days",
        "retention",
        "Embedding cache retention",
        "int",
        30,
        "Days to keep persistent embedding-cache rows after last use.",
        min=0,
        max=3650,
    ),
    _spec(
        "audit_log_retention_days",
        "retention",
        "Audit log retention",
        "int",
        365,
        "Days to keep audit events.",
        min=1,
        max=3650,
    ),
)

REGISTRY = {spec.key: spec for spec in SETTING_SPECS}

REGISTRY = {spec.key: spec for spec in SETTING_SPECS}
