"""Type definitions for the bigRAG Python SDK.

All types are re-exported here for convenience.
"""

from bigrag.types.access import (
    AccessLogBucket,
    AccessLogEntry,
    AccessLogListResponse,
    AccessLogOverviewResponse,
    AccessLogTimelinePoint,
)
from bigrag.types.admin import (
    ApiKey,
    ApiKeyListResponse,
    AuditLogEntry,
    AuditLogListResponse,
    CreateApiKeyBody,
    CreateApiKeyResponse,
    CreateEmbeddingPresetBody,
    CreateMcpServerBody,
    CreateMcpServerResponse,
    CreateUserBody,
    EmbeddingPreset,
    EmbeddingPresetListResponse,
    McpServer,
    McpServerListResponse,
    UpdateApiKeyBody,
    UpdateEmbeddingPresetBody,
    UpdateMcpServerBody,
    UpdateUserBody,
    UserListResponse,
)
from bigrag.types.analytics import AnalyticsResponse, PeriodStats, TopQuery
from bigrag.types.auth import (
    ChangePasswordBody,
    LoginBody,
    PreferencesResponse,
    SessionResponse,
    SetupBody,
    SetupStatusResponse,
    User,
    WhoamiResponse,
)
from bigrag.types.chat import (
    ChatBody,
    ChatConversation,
    ChatCreateResponse,
    ChatDetailResponse,
    ChatListResponse,
    ChatMessage,
    ChatSource,
    ChatStreamEvent,
)
from bigrag.types.collections import (
    Collection,
    CollectionListResponse,
    CollectionStatsResponse,
    CreateCollectionBody,
    UpdateCollectionBody,
)
from bigrag.types.common import (
    DocumentStats,
    HealthResponse,
    PlatformStatsResponse,
    QueueStatsResponse,
    ReadinessResponse,
    StatusResponse,
)
from bigrag.types.connectors import (
    ConnectorAccountStatus,
    ConnectorSourceStatus,
    ConnectorSourceType,
    ConnectorSyncStatus,
    ConnectorSyncTrigger,
    CreateGoogleSourceBody,
    GoogleAccount,
    GoogleConnectorConfig,
    GoogleDriveFile,
    GoogleDriveFileListResponse,
    GoogleOAuthStartUrlResponse,
    GoogleProvider,
    GoogleSource,
    GoogleSourceListResponse,
    GoogleSyncJob,
    GoogleSyncJobListResponse,
    UpdateGoogleConnectorConfigBody,
    UpdateGoogleSourceBody,
)
from bigrag.types.documents import (
    BatchDeleteDocumentsResponse,
    BatchDeleteError,
    BatchGetDocumentsResponse,
    BatchStatusResponse,
    Document,
    DocumentChunk,
    DocumentChunkListResponse,
    DocumentListResponse,
    DocumentStatus,
)
from bigrag.types.embeddings import EmbeddingModelInfo, EmbeddingModelListResponse
from bigrag.types.evaluations import EvalBody, EvalCase, EvalPerCase, EvalResponse
from bigrag.types.query import (
    BatchQueryBody,
    BatchQueryItem,
    BatchQueryResponse,
    BatchQueryResultItem,
    MultiQueryBody,
    MultiQueryResponse,
    MultiQueryResult,
    QueryBody,
    QueryResponse,
    QueryResult,
    QueryTimings,
)
from bigrag.types.sse import ProgressEvent
from bigrag.types.usage import CollectionUsage, UsageResponse
from bigrag.types.vectors import DeleteResponse, UpsertResponse, VectorEntry
from bigrag.types.webhooks import (
    CreateWebhookBody,
    CreateWebhookResponse,
    UpdateWebhookBody,
    Webhook,
    WebhookDelivery,
    WebhookDeliveryListResponse,
    WebhookListResponse,
    WebhookTestResponse,
)

__all__ = [
    # Common
    "StatusResponse",
    "HealthResponse",
    "ReadinessResponse",
    "QueueStatsResponse",
    "DocumentStats",
    "PlatformStatsResponse",
    # Auth
    "SetupStatusResponse",
    "LoginBody",
    "SetupBody",
    "ChangePasswordBody",
    "User",
    "SessionResponse",
    "WhoamiResponse",
    "PreferencesResponse",
    # Chat
    "ChatBody",
    "ChatSource",
    "ChatMessage",
    "ChatConversation",
    "ChatListResponse",
    "ChatDetailResponse",
    "ChatCreateResponse",
    "ChatStreamEvent",
    # Admin
    "UserListResponse",
    "CreateUserBody",
    "UpdateUserBody",
    "ApiKey",
    "CreateApiKeyBody",
    "CreateApiKeyResponse",
    "UpdateApiKeyBody",
    "ApiKeyListResponse",
    "AuditLogEntry",
    "AuditLogListResponse",
    "EmbeddingPreset",
    "CreateEmbeddingPresetBody",
    "UpdateEmbeddingPresetBody",
    "EmbeddingPresetListResponse",
    "McpServer",
    "CreateMcpServerBody",
    "UpdateMcpServerBody",
    "CreateMcpServerResponse",
    "McpServerListResponse",
    "AccessLogEntry",
    "AccessLogListResponse",
    "AccessLogBucket",
    "AccessLogTimelinePoint",
    "AccessLogOverviewResponse",
    # Collections
    "Collection",
    "CollectionListResponse",
    "CollectionStatsResponse",
    "CreateCollectionBody",
    "UpdateCollectionBody",
    # Connectors
    "GoogleProvider",
    "ConnectorAccountStatus",
    "ConnectorSourceStatus",
    "ConnectorSourceType",
    "ConnectorSyncTrigger",
    "ConnectorSyncStatus",
    "GoogleConnectorConfig",
    "UpdateGoogleConnectorConfigBody",
    "GoogleAccount",
    "GoogleDriveFile",
    "GoogleDriveFileListResponse",
    "GoogleOAuthStartUrlResponse",
    "CreateGoogleSourceBody",
    "UpdateGoogleSourceBody",
    "GoogleSource",
    "GoogleSourceListResponse",
    "GoogleSyncJob",
    "GoogleSyncJobListResponse",
    # Documents
    "Document",
    "DocumentListResponse",
    "DocumentChunk",
    "DocumentChunkListResponse",
    "DocumentStatus",
    "BatchStatusResponse",
    "BatchGetDocumentsResponse",
    "BatchDeleteError",
    "BatchDeleteDocumentsResponse",
    # Query
    "QueryBody",
    "QueryResult",
    "QueryTimings",
    "QueryResponse",
    "MultiQueryBody",
    "MultiQueryResult",
    "MultiQueryResponse",
    "BatchQueryItem",
    "BatchQueryBody",
    "BatchQueryResultItem",
    "BatchQueryResponse",
    # Evaluations
    "EvalCase",
    "EvalBody",
    "EvalPerCase",
    "EvalResponse",
    # Vectors
    "VectorEntry",
    "UpsertResponse",
    "DeleteResponse",
    # Webhooks
    "Webhook",
    "CreateWebhookBody",
    "CreateWebhookResponse",
    "UpdateWebhookBody",
    "WebhookListResponse",
    "WebhookDelivery",
    "WebhookDeliveryListResponse",
    "WebhookTestResponse",
    # Analytics
    "PeriodStats",
    "TopQuery",
    "AnalyticsResponse",
    # Embeddings
    "EmbeddingModelInfo",
    "EmbeddingModelListResponse",
    # Usage
    "CollectionUsage",
    "UsageResponse",
    # SSE
    "ProgressEvent",
]
